# Generated by Django 4.0.6 on 2022-07-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvid',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
