# Generated by Django 4.0.6 on 2022-07-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0002_alter_uploadvid_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='adviserlogo',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='award',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='media',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='whylearn',
            name='thumb',
            field=models.ImageField(upload_to='images'),
        ),
    ]
