# Generated by Django 4.0.6 on 2022-07-25 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0006_remove_technologylist_name_technology_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='list',
        ),
        migrations.AddField(
            model_name='technologylist',
            name='name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='solution_page.technology'),
            preserve_default=False,
        ),
    ]
