# Generated by Django 4.0.6 on 2022-07-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0007_remove_technology_list_technologylist_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Methods',
            new_name='Method',
        ),
    ]
