# Generated by Django 4.0.6 on 2022-07-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0011_adviserlink_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='logo',
            field=models.ImageField(default='1', upload_to='images'),
            preserve_default=False,
        ),
    ]
