# Generated by Django 4.0.6 on 2022-07-29 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0014_modalregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalregister',
            name='date_of_birth',
        ),
    ]
