# Generated by Django 4.0.6 on 2022-07-29 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0015_alter_modalregister_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalregister',
            name='date_of_birth',
            field=models.SmallIntegerField(default=2010, validators=[django.core.validators.MaxValueValidator(2016), django.core.validators.MinValueValidator(2010)]),
        ),
    ]
