# Generated by Django 4.0.6 on 2022-08-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0016_modalregister_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
