# Generated by Django 4.0.6 on 2022-08-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0018_remove_user_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
