# Generated by Django 4.0.6 on 2022-08-02 06:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0019_delete_loginuser_delete_registeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
