# Generated by Django 4.0.6 on 2022-08-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0020_alter_method_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
