# Generated by Django 4.0.6 on 2022-08-02 07:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0021_method_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='intro',
            field=tinymce.models.HTMLField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='subcontent',
            field=tinymce.models.HTMLField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='maincontent',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='titlename',
            field=tinymce.models.HTMLField(),
        ),
    ]
