# Generated by Django 4.0.6 on 2022-08-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0022_certificate_intro_certificate_subcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='usercount',
            field=models.IntegerField(default=0),
        ),
    ]
