# Generated by Django 4.0.6 on 2022-08-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0023_project_usercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution_page.whylearn')),
            ],
        ),
    ]
