# Generated by Django 4.0.6 on 2022-08-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0025_whylearn_count_whylearn_subdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='whylearn',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
