# Generated by Django 4.0.6 on 2022-08-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0029_alter_adviserlink_title_alter_usercount_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviserlink',
            name='logo',
        ),
        migrations.AddField(
            model_name='adviserlink',
            name='link',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
