# Generated by Django 4.0.6 on 2022-08-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0030_remove_adviserlink_logo_adviserlink_link'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadvid',
            table='Upload Vid',
        ),
    ]
