# Generated by Django 4.0.6 on 2022-08-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0033_whychooseus_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviser',
            options={'verbose_name_plural': 'Đội ngũ cố vấn'},
        ),
        migrations.AlterModelOptions(
            name='adviserlogo',
            options={'verbose_name_plural': 'Đội ngũ chuyên gia đối tác'},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name_plural': 'Thành tích & giải thưởng'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'Chứng nhận chất lượng quốc tế'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Khóa học công nghệ'},
        ),
        migrations.AlterModelOptions(
            name='learningpath',
            options={'get_latest_by': ['img'], 'verbose_name_plural': 'Lộ trình học tập'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Báo chí nói về chúng tôi'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'verbose_name_plural': 'Phương pháp sư phạm'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name_plural': 'Học sinh, phụ huynh nói gì về Teky'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Dự án tiêu biểu'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Nền tảng công nghệ'},
        ),
        migrations.AlterModelOptions(
            name='uploadvid',
            options={'get_latest_by': ['title', 'url', 'img', 'quote', 'name'], 'verbose_name_plural': 'Thế kỉ 21 - Trẻ em cần học lập trình'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Thư viện hình ảnh'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name_plural': 'Vì sao chọn Teky'},
        ),
        migrations.AlterModelOptions(
            name='whylearn',
            options={'verbose_name_plural': 'Trẻ em cần học lập trình'},
        ),
        migrations.AddField(
            model_name='adviser',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adviserlogo',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='award',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parent',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whylearn',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
