# Generated by Django 4.0.6 on 2022-08-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0034_alter_adviser_options_alter_adviserlogo_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCount',
            new_name='UserIcon',
        ),
    ]
