# Generated by Django 4.0.6 on 2022-08-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0036_whylearn_vote_alter_whylearn_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='projecticon',
            name='NameIcon',
            field=models.ManyToManyField(related_name='nameicon', to='solution_page.nameicon'),
        ),
    ]
