# Generated by Django 4.0.6 on 2022-08-06 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0038_remove_projecticon_nameicon_projecticon_nameicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecticon',
            name='img',
        ),
    ]
