# Generated by Django 4.0.6 on 2022-08-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0039_remove_projecticon_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adviserlink',
            old_name='link',
            new_name='logo',
        ),
    ]
