# Generated by Django 4.0.6 on 2022-08-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0040_rename_link_adviserlink_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviserlink',
            name='logo',
        ),
    ]
