# Generated by Django 4.0.6 on 2022-08-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0041_remove_adviserlink_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviserlink',
            name='logo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='solution_page.nameicon'),
            preserve_default=False,
        ),
    ]
