# Generated by Django 4.0.6 on 2022-08-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0042_adviserlink_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameicon',
            options={'verbose_name_plural': 'Icon'},
        ),
        migrations.RemoveField(
            model_name='projecticon',
            name='NameIcon',
        ),
        migrations.AddField(
            model_name='projecticon',
            name='NameIcon',
            field=models.ManyToManyField(to='solution_page.nameicon'),
        ),
    ]
