# Generated by Django 4.0.6 on 2022-08-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0043_alter_nameicon_options_remove_projecticon_nameicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecticon',
            name='NameIcon',
        ),
    ]
