# Generated by Django 4.0.6 on 2022-08-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0045_projecticon_nameicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Vì sao chọn Teky'},
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
