# Generated by Django 4.0.6 on 2022-08-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0046_alter_whychooseus_options_whychooseus_my_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseus',
            name='order',
        ),
    ]
