# Generated by Django 4.0.6 on 2022-08-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0047_remove_whychooseus_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Nền tảng công nghệ'},
        ),
        migrations.RemoveField(
            model_name='technology',
            name='order',
        ),
        migrations.AddField(
            model_name='technology',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
