# Generated by Django 4.0.6 on 2022-08-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0050_alter_adviser_options_alter_adviserlink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviserlogo',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Đội ngũ chuyên gia đối tác'},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Thành tích & giải thưởng'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Khóa học công nghệ'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Báo chí nói về chúng tôi'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Học sinh, phụ huynh nói gì về Teky'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Dự án tiêu biểu'},
        ),
        migrations.AlterModelOptions(
            name='projecticon',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Thư viện hình ảnh'},
        ),
        migrations.AlterModelOptions(
            name='usericon',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='whylearn',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'Trẻ em cần học lập trình'},
        ),
        migrations.RemoveField(
            model_name='adviserlogo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='award',
            name='order',
        ),
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
        migrations.RemoveField(
            model_name='media',
            name='order',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.RemoveField(
            model_name='user',
            name='order',
        ),
        migrations.RemoveField(
            model_name='whylearn',
            name='order',
        ),
        migrations.AddField(
            model_name='adviserlogo',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='award',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parent',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projecticon',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usericon',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whylearn',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
