# Generated by Django 4.0.6 on 2022-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0051_alter_adviserlogo_options_alter_award_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningpath',
            options={'get_latest_by': ['img'], 'ordering': ['my_order'], 'verbose_name_plural': 'Lộ trình học tập'},
        ),
        migrations.AddField(
            model_name='learningpath',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
