# Generated by Django 4.0.6 on 2022-08-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0052_alter_learningpath_options_learningpath_my_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bordercolor', models.CharField(max_length=50)),
            ],
        ),
    ]
