# Generated by Django 4.0.6 on 2022-08-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0053_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='bordercolor',
            new_name='name',
        ),
    ]
