# Generated by Django 4.0.6 on 2022-08-13 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution_page', '0054_rename_bordercolor_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='whylearn',
            name='color',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='color', to='solution_page.color'),
            preserve_default=False,
        ),
    ]
